
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author el_ma
 */
public class Deposito extends javax.swing.JFrame {

    /**
     * Creates new form Deposito
     */
    public Deposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrdb_depo_corriente = new javax.swing.JRadioButton();
        jrdb_depo_ahorro = new javax.swing.JRadioButton();
        jtxt_monto_deposito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtn_enviar_deposito = new javax.swing.JButton();
        jbtn_salir_deposito = new javax.swing.JButton();
        jlbl_realizado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setText("Seleccione tipo de cuenta:");

        jrdb_depo_corriente.setBackground(new java.awt.Color(0, 255, 204));
        buttonGroup1.add(jrdb_depo_corriente);
        jrdb_depo_corriente.setText("Cuenta corriente");

        jrdb_depo_ahorro.setBackground(new java.awt.Color(0, 255, 204));
        buttonGroup1.add(jrdb_depo_ahorro);
        jrdb_depo_ahorro.setText("Cuenta de ahorro");

        jLabel2.setText("Monto a depositar :");

        jbtn_enviar_deposito.setText("Enviar");
        jbtn_enviar_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enviar_depositoActionPerformed(evt);
            }
        });

        jbtn_salir_deposito.setText("Volver");
        jbtn_salir_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir_depositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbtn_enviar_deposito)
                        .addGap(53, 53, 53)
                        .addComponent(jbtn_salir_deposito))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrdb_depo_ahorro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbl_realizado)
                                .addGap(245, 245, 245)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(184, 184, 184))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrdb_depo_corriente)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_monto_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdb_depo_corriente)
                    .addComponent(jrdb_depo_ahorro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_monto_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jlbl_realizado)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_enviar_deposito)
                    .addComponent(jbtn_salir_deposito))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Realizar depósito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_enviar_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enviar_depositoActionPerformed
        try {
            if(this.jrdb_depo_corriente.isSelected() || this.jrdb_depo_ahorro.isSelected()){
                if (this.jrdb_depo_corriente.isSelected() && Util.lista.get(Util.usuarioConectado()).isTieneCorriente()) {
                    if (Integer.parseInt(jtxt_monto_deposito.getText()) > 0) {
                        Util.lista.get(Util.usuarioConectado()).setSaldoCorriente(Util.lista.get(Util.usuarioConectado()).getSaldoCorriente() + Integer.parseInt(jtxt_monto_deposito.getText()));
                        JOptionPane.showMessageDialog(this, "Su nuevo saldo de cuenta corriente es : "+Util.lista.get(Util.usuarioConectado()).getSaldoCorriente(), "Operacion Realizada", 1);                        
                    } else {
                        JOptionPane.showMessageDialog(this, "El deposito debe ser mayor a 0", "Error", 0);
                    }
                } else if(this.jrdb_depo_ahorro.isSelected() && Util.lista.get(Util.usuarioConectado()).isTieneAhorro()){
                    if (Integer.parseInt(jtxt_monto_deposito.getText()) > 0) {
                        Util.lista.get(Util.usuarioConectado()).setSaldoAhorro(Util.lista.get(Util.usuarioConectado()).getSaldoAhorro() + Integer.parseInt(jtxt_monto_deposito.getText()));
                        JOptionPane.showMessageDialog(this, "Su nuevo saldo de cuenta Ahorro es : "+Util.lista.get(Util.usuarioConectado()).getSaldoAhorro(), "Operacion Realizada", 1);
                       
                    } else {
                        JOptionPane.showMessageDialog(this, "El deposito debe ser mayor a 0", "Error", 0);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No selecciono cuenta", "Error", 0);
            }
            
        } catch (Exception e) {
            System.out.println("Error depositoActionPerformed: "+e.getMessage());
        }
    }//GEN-LAST:event_jbtn_enviar_depositoActionPerformed

    private void jbtn_salir_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir_depositoActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salir_depositoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Deposito().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_enviar_deposito;
    private javax.swing.JButton jbtn_salir_deposito;
    private javax.swing.JLabel jlbl_realizado;
    private javax.swing.JRadioButton jrdb_depo_ahorro;
    private javax.swing.JRadioButton jrdb_depo_corriente;
    private javax.swing.JTextField jtxt_monto_deposito;
    // End of variables declaration//GEN-END:variables
}
