

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author el_ma
 */
public class Giro extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Giro
     */
    public Giro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrdb_giro_corriente = new javax.swing.JRadioButton();
        jrdb_giro_ahorro = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jtxt_monto_giro = new javax.swing.JTextField();
        jbtn_enviar_giro = new javax.swing.JButton();
        jbtn_salir_giro = new javax.swing.JButton();
        jlbl_realizado = new javax.swing.JLabel();
        jlbl_saldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Seleccione tipo de cuenta:");

        jrdb_giro_corriente.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(jrdb_giro_corriente);
        jrdb_giro_corriente.setText("Cuenta corriente");
        jrdb_giro_corriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb_giro_corrienteActionPerformed(evt);
            }
        });

        jrdb_giro_ahorro.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(jrdb_giro_ahorro);
        jrdb_giro_ahorro.setText("Cuenta de ahorro");
        jrdb_giro_ahorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb_giro_ahorroActionPerformed(evt);
            }
        });

        jLabel2.setText("Monto a girar:");

        jbtn_enviar_giro.setText("Enviar");
        jbtn_enviar_giro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enviar_giroActionPerformed(evt);
            }
        });

        jbtn_salir_giro.setText("Volver");
        jbtn_salir_giro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir_giroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jrdb_giro_ahorro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jrdb_giro_corriente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_monto_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jlbl_saldo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_realizado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jbtn_enviar_giro)
                                .addGap(42, 42, 42)
                                .addComponent(jbtn_salir_giro)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdb_giro_corriente)
                    .addComponent(jrdb_giro_ahorro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_monto_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_realizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_saldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_enviar_giro)
                    .addComponent(jbtn_salir_giro))
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Realizar Giro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_enviar_giroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enviar_giroActionPerformed

        try {
            if(this.jrdb_giro_corriente.isSelected() || this.jrdb_giro_ahorro.isSelected()){
                if (this.jrdb_giro_corriente.isSelected() && Util.lista.get(Util.usuarioConectado()).isTieneCorriente()) {
                    if ((Util.lista.get(Util.usuarioConectado()).getSaldoCorriente() - Integer.parseInt(jtxt_monto_giro.getText())) >= -500000) {
                        Util.lista.get(Util.usuarioConectado()).setSaldoCorriente(Util.lista.get(Util.usuarioConectado()).getSaldoCorriente() - Integer.parseInt(jtxt_monto_giro.getText()));
                        this.jlbl_realizado.setText("Operación realizada");
                        actualizarSaldoCorriente();
                    } else {
                        JOptionPane.showMessageDialog(this, "Supera limite del crédito", "Error", 0);
                    }
                } else if(this.jrdb_giro_ahorro.isSelected() && Util.lista.get(Util.usuarioConectado()).isTieneAhorro()){
                    if ((Util.lista.get(Util.usuarioConectado()).getSaldoAhorro() - Integer.parseInt(jtxt_monto_giro.getText())) >= 0) {
                        Util.lista.get(Util.usuarioConectado()).setSaldoAhorro(Util.lista.get(Util.usuarioConectado()).getSaldoAhorro() - Integer.parseInt(jtxt_monto_giro.getText()));
                        this.jlbl_realizado.setText("Operación realizada");
                        actualizarSaldoAhorro();
                    } else {
                        JOptionPane.showMessageDialog(this, "El monto no puede ser mayor al saldo", "Error", 0);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No selecciono cuenta", "Error", 0);
            }
            
        } catch (Exception e) {
            System.out.println("Error giroActionPerformed: "+e.getMessage());
        }
//        try {
//            if (this.jrdb_giro_corriente.isSelected()) {
//                if (Cliente.saldoCorriente > -500000) {
//                    int giroCorriente = Cliente.saldoCorriente - Integer.parseInt(jtxt_monto_giro.getText());
//                    if (giroCorriente > -500000) {
//                        this.jlbl_realizado.setText("Operacion realizada");
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Supera el limite del credito", "Error", 0);
//                    }
//                    this.jlbl_realizado.setText("Operación realizada");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Supera limite del crédito", "Error", 0);
//                }
//            } else if (this.jrdb_giro_ahorro.isSelected()) {
//                if (Cliente.saldoAhorro > 0) {
//                    if (Integer.parseInt(jtxt_monto_giro.getText()) < Cliente.saldoAhorro + 1) {
//                        int giroAhorro = Cliente.saldoAhorro - Integer.parseInt(jtxt_monto_giro.getText());
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Debe ingresar un monto", "Error de monto", 0);
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de cuenta", "Error", 0);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Debe ingresar un monto", "Error de monto", 0);
//        }


    }//GEN-LAST:event_jbtn_enviar_giroActionPerformed

    
    public void enviarMonto(){
        int j = 0;
        for (int i = 0; i < Util.lista.size(); i++) {
            if (Util.lista.get(i).getRut() == Util.rutsesion) {
                j = i;
                break;
            }
        }
    }
    
    private void jbtn_salir_giroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir_giroActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salir_giroActionPerformed

    private void jrdb_giro_corrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb_giro_corrienteActionPerformed
        if (Util.lista.get(Util.usuarioConectado()).isTieneCorriente()) {
            actualizarSaldoCorriente();
        }
        
    }//GEN-LAST:event_jrdb_giro_corrienteActionPerformed

    private void jrdb_giro_ahorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb_giro_ahorroActionPerformed
        if (Util.lista.get(Util.usuarioConectado()).isTieneAhorro()) {
            actualizarSaldoAhorro();
        }
    }//GEN-LAST:event_jrdb_giro_ahorroActionPerformed

    private void actualizarSaldoCorriente(){
        this.jlbl_saldo.setText("Saldo : " + Util.lista.get(Util.usuarioConectado()).sCorriente());
    }
    
    private void actualizarSaldoAhorro(){
        this.jlbl_saldo.setText("Saldo : " + Util.lista.get(Util.usuarioConectado()).sAhorro());
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Giro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Giro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Giro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Giro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Giro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_enviar_giro;
    private javax.swing.JButton jbtn_salir_giro;
    private javax.swing.JLabel jlbl_realizado;
    private javax.swing.JLabel jlbl_saldo;
    private javax.swing.JRadioButton jrdb_giro_ahorro;
    private javax.swing.JRadioButton jrdb_giro_corriente;
    private javax.swing.JTextField jtxt_monto_giro;
    // End of variables declaration//GEN-END:variables
}
