
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author el_ma
 */
public class Saldos extends javax.swing.JFrame {

    
    // = new Cliente(4321, "wena", "chau", 3000, 40000);

    /**
     * Creates new form Saldos
     */
    public Saldos() {
//        cliente1 = new Cliente(1234, "hola", "adios", 10000, 20000, true, true);
//        cliente2 = new Cliente(4321, "wena", "adios", 11000, 0, true, false);
//        Util.lista.add(cliente1);
//        Util.lista.add(cliente2);
        initComponents();
        cargarNombre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlbl_nombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_info_saldo = new javax.swing.JTable();
        jbtn_consultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jchk_corriente = new javax.swing.JCheckBox();
        jchk_ahorro = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_deposito = new javax.swing.JMenuItem();
        jmi_giro = new javax.swing.JMenuItem();
        jmi_cerrar = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        jlbl_nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbl_nombre.setText("Bienvenido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jlbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jtbl_info_saldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Apellido", "Tipo de cuenta", "Saldo de cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtbl_info_saldo);

        jbtn_consultar.setText("Consultar");
        jbtn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_consultarActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione tipo de cuenta :");

        jchk_corriente.setText("Cuenta corriente");

        jchk_ahorro.setText("Cuenta de ahorro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchk_corriente)
                                .addGap(18, 18, 18)
                                .addComponent(jchk_ahorro))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jbtn_consultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchk_corriente)
                    .addComponent(jchk_ahorro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_consultar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setText("Acciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmi_deposito.setText("Realizar depósito");
        jmi_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_depositoActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_deposito);

        jmi_giro.setText("Realizar giro");
        jmi_giro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_giroActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_giro);

        jmi_cerrar.setText("Cerrar sesión");
        jmi_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cerrarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_cerrar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_depositoActionPerformed
        new Deposito().setVisible(true);
    }//GEN-LAST:event_jmi_depositoActionPerformed

    private void jmi_giroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_giroActionPerformed
        new Giro().setVisible(true);
    }//GEN-LAST:event_jmi_giroActionPerformed

    private void jbtn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_consultarActionPerformed
        String matris[][] = new String[0][0];
        int aux = Util.usuarioConectado();
        jtbl_info_saldo.setModel(new javax.swing.table.DefaultTableModel(
                matris,
                new String[]{
                    "Rut", "Nombre", "Apellido", "Tipo de cuenta" , "Saldo de cuenta"
                }
        ));
        if (Util.lista.get(aux).isTieneAhorro() || Util.lista.get(aux).isTieneCorriente()) {
            if (jchk_ahorro.isSelected() || jchk_corriente.isSelected()) {
            if (Util.lista.get(aux).isTieneAhorro() && jchk_ahorro.isSelected() && !jchk_corriente.isSelected())  {
                mostrarAhorro();
            } else if(Util.lista.get(aux).isTieneCorriente() && jchk_corriente.isSelected() && !jchk_ahorro.isSelected()){
                mostrarCorriente();
            } else if(Util.lista.get(aux).isTieneAhorro() && Util.lista.get(aux).isTieneCorriente() && jchk_ahorro.isSelected() && jchk_corriente.isSelected()){
                mostrarAmbas();
//                mostrarAhorro();
//                mostrarCorriente();
            }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de cuenta", "Error de cuenta", 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No tiene cuentas para consultar", "Error", 0);
        }
    
        

//        if (this.jchk_ahorro.isSelected()) {
//            mostrarAhorro();
//        } else if(this.jchk_corriente.isSelected()){
//            mostrarCorriente();
//        } else if(this.jchk_ahorro.isSelected() && this.jchk_corriente.isSelected()){
//            mostrarCorriente();
//            mostrarAhorro();
//        } else {
//            JOptionPane.showMessageDialog(null, "Seleccione un tipo de cuenta", "Error", 0);
//        }
    }//GEN-LAST:event_jbtn_consultarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmi_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cerrarActionPerformed
        Util.rutsesion = -1;
        new IngresarUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jmi_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Saldos().setVisible(true);
//            }
//        });
//    }

    public void mostrarAhorro() {
        String matris[][] = new String[1][5];
            matris[0][0] = Util.lista.get(Util.usuarioConectado()).rutens();
            matris[0][1] = Util.lista.get(Util.usuarioConectado()).getNombre();
            matris[0][2] = Util.lista.get(Util.usuarioConectado()).getApellido();
            matris[0][3] = "Cuenta de Ahorro";
            matris[0][4] = Util.lista.get(Util.usuarioConectado()).sAhorro();
        
        
        jtbl_info_saldo.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Rut", "Nombre", "Apellido", "Tipo de cuenta" , "Saldo de cuenta"
            }
        ));    
    }
    
    public void mostrarCorriente(){
        String matris[][] = new String[1][5];
            matris[0][0] = Util.lista.get(Util.usuarioConectado()).rutens();
            matris[0][1] = Util.lista.get(Util.usuarioConectado()).getNombre();
            matris[0][2] = Util.lista.get(Util.usuarioConectado()).getApellido();
            matris[0][3] = "Cuenta corriente";
            matris[0][4] = Util.lista.get(Util.usuarioConectado()).sCorriente();
        
        
        jtbl_info_saldo.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Rut", "Nombre", "Apellido", "Tipo de cuenta" , "Saldo de cuenta"
            }
        ));
    }
    
    public void mostrarAmbas(){
        String matris[][] = new String[1][6];
            matris[0][0] = Util.lista.get(Util.usuarioConectado()).rutens();
            matris[0][1] = Util.lista.get(Util.usuarioConectado()).getNombre();
            matris[0][2] = Util.lista.get(Util.usuarioConectado()).getApellido();
            matris[0][3] = "Ambas cuentas";
            matris[0][4] = Util.lista.get(Util.usuarioConectado()).sCorriente();
            matris[0][5] = Util.lista.get(Util.usuarioConectado()).sAhorro();
        
        jtbl_info_saldo.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Rut", "Nombre", "Apellido", "Tipo de cuenta" , "Saldo de cuenta corriente", "Saldo de cuenta de ahorro"
            }
        ));
    
    }
    
    public void cargarNombre(){
        this.jlbl_nombre.setText("Bienvenido " + Util.lista.get(Util.usuarioConectado()).getNombre() + " " + Util.lista.get(Util.usuarioConectado()).getApellido());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn_consultar;
    private javax.swing.JCheckBox jchk_ahorro;
    private javax.swing.JCheckBox jchk_corriente;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JMenuItem jmi_cerrar;
    private javax.swing.JMenuItem jmi_deposito;
    private javax.swing.JMenuItem jmi_giro;
    private javax.swing.JTable jtbl_info_saldo;
    // End of variables declaration//GEN-END:variables
}
